# Generated by Django 4.2 on 2024-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                # ('app', models.CharField(default='cis', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('Students', 'Students'), ('High Schools', 'High Schools'), ('Classes', 'Classes'), ('Misc.', 'Misc.'), ('Instructors', 'Instructors')], max_length=100)),
                ('available_for', multiselectfield.db.fields.MultiSelectField(choices=[('ce', 'EC Staff'), ('highschool_admin', 'High School Administrator'), ('instructor', 'Instructor')], max_length=30)),
            ],
            options={
                'unique_together': {('name', 'categories')},
            },
        ),
        migrations.CreateModel(
            name='ReportScheduler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('ran_on', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ran', 'Ran')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.report')),
            ],
        ),
    ]
