# Generated by Django 4.2 on 2024-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_report_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='app',
            field=models.CharField(default='cis', max_length=100),
        ),
    ]
