# Generated by Django 4.2 on 2026-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportscheduler',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ran', 'Ran'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
